version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: math_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis_queue
    ports:
      - "6379:6379"

  # --- BACKEND (Офіціанти) ---
  backend:
    build: .
    # command: забираємо --reload, бо в продакшені (з кількома серверами) це заважає
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    # !!! МИ ПРИБРАЛИ PORTS !!!
    # Тепер до бекенду не можна достукатися напряму з Windows.
    # Тільки через Nginx.

  # --- WORKER (Кухарі) ---
  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # --- NGINX (Адміністратор) - НОВЕ ---
  nginx:
    image: nginx:latest
    container_name: my_load_balancer
    volumes:
      # Підключаємо наш файл налаштувань всередину контейнера
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Тепер ми заходимо через порт 80 (стандартний), а не 8000
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: